defmodule LLMDb.Application do
  @moduledoc """
  OTP Application for LLMDb.

  Automatically loads the pre-built snapshot on application start.
  The snapshot is generated by `mix llm_db.build` and packaged
  with the release.
  """

  use Application

  @impl true
  def start(_type, _args) do
    case LLMDb.load() do
      {:ok, _snapshot} -> {:ok, self()}
      {:error, reason} -> {:error, reason}
    end
  end
end
